### ISSUE TITLE
SessionID attributes should be SessionId

### ISSUE THREAD

**Issue by HUG-socloz** [AymDev/MessengerAzureBundle#3]
We can use session enabled queues by using "Forward messages to". But the SessionID should be SessionId

The message is not forward and goes directly to dead-letter with the error : "The SessionId was not set on a message, and it cannot be sent to the entity. Entities that have session support enabled can only receive messages that have the SessionId set to a valid value."

**Comment by AymDev** [comment]
Thanks for the fix in #4 
The CI checks were KO but it was my fault, I fixed it before merging the PR and now it's all green.
